# Generated by Django 6.0.4 on 2026-04-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Plage choisie par le bénévole (dans les limites du créneau)', verbose_name='Début choisi')),
                ('end_date', models.DateTimeField(verbose_name='Fin choisie')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('backup', 'Secours')], default='confirmed', max_length=20, verbose_name='Statut')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['start_date'],
                'unique_together': {('user', 'slot')},
            },
        ),
    ]
