# Generated by Django 6.0.4 on 2026-05-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvitation',
            name='token',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
    ]
