# Generated by Django 6.0.4 on 2026-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventinvitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
    ]
