# Generated by Django 6.0.4 on 2026-05-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventinvitation_is_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='event_posters/', verbose_name='Affiche'),
        ),
    ]
