# Generated by Django 6.0.4 on 2026-05-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
