# Generated by Django 6.0.4 on 2026-04-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Nom affiché dans les plannings. Si vide : « Prénom L. ».', max_length=60, verbose_name='Surnom'),
        ),
    ]
