# Generated by Django 6.0.4 on 2026-04-25 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('min_volunteers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Min bénévoles')),
                ('max_volunteers', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max bénévoles')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(verbose_name='Début')),
                ('end_date', models.DateTimeField(verbose_name='Fin')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Null = illimité', null=True, verbose_name='Capacité')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Créneau',
                'verbose_name_plural': 'Créneaux',
                'ordering': ['start_date', 'order'],
            },
        ),
    ]
