# Generated by Django 6.0.4 on 2026-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='org_logos/', verbose_name='Logo'),
        ),
    ]
