# Generated by Django 6.0.4 on 2026-05-24 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationinvitation_decoration_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('target_url', models.URLField(max_length=2000)),
                ('decoration_type', models.CharField(choices=[('logo', "Logo de l'association"), ('text', 'Texte personnalisé')], default='logo', max_length=8)),
                ('decoration_text', models.CharField(blank=True, max_length=15)),
                ('decoration_bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('decoration_text_color', models.CharField(default='#000000', max_length=7)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_qrs', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'QR code externe',
                'verbose_name_plural': 'QR codes externes',
                'ordering': ['-created_at'],
            },
        ),
    ]
